version: '3.8'
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: candidate_management
      POSTGRES_PASSWORD: root
      POSTGRES_USERNAME: root
    restart: always
  backend:
    build:
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_URL: jdbc:postgresql://localhost:5432/candidate_management
    depends_on:
      - db
    restart: always